version: '3'
services:
  time_app:
    image: time_app
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - "./:/app"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /static:/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - time_app